//
//  AnnuaireModel.m
//  Celaneo1
//
//  Created by Sebastien Chauvin on 6/20/11.
//  Copyright 2011 __MyCompanyName__. All rights reserved.
//

#import "AnnuaireModel.h"

#import "CollateAndSearch.h"
#import "Personne.h"

@interface AnnuaireModel()
- (NSArray *)partitionObjects:(NSArray *)array collationStringSelector:(SEL)selector;
@property (nonatomic, retain) NSArray* filteredData;
@end

@implementation AnnuaireModel

@synthesize filteredData;
@synthesize filtered;
@synthesize indexShown;

- (id) init
{
    NSArray* prenoms = [NSArray arrayWithObjects:@"ABE", 
                        @"ABEL", 
                        @"ABRAHAM", 
                        @"ABRAM", 
                        @"ADALBERTO", 
                        @"ADAM", 
                        @"ADAN", 
                        @"ADOLFO", 
                        @"ALDOLPH", 
                        @"AlDRIAN", 
                        @"AGUSTIN", 
                        @"AHMAD", 
                        @"AHMED", 
                        @"AL", 
                        @"ALAN", 
                        @"ALBERT", 
                        @"ALBERTO", 
                        @"ALDEN", 
                        @"ALDO", 
                        @"ALEC", 
                        @"ALEJANDRO", 
                        @"ALEX", 
                        @"ALEXANDER", 
                        @"ALEXIS", 
                        @"ALFONSO", 
                        @"ALFONZO", 
                        @"ALFRED", 
                        @"ALFREDO", 
                        @"ALI", 
                        @"ALLAN", 
                        @"ALLEN", 
                        @"ALONSO", 
                        @"ALONZO", 
                        @"ALPHONSE", 
                        @"ALPHONSO", 
                        @"ALTON", 
                        @"ALVA", 
                        @"ALVARO", 
                        @"ALVIN", 
                        @"AMADO", 
                        @"AMBROSE", 
                        @"AMOS", 
                        @"ANDERSON", 
                        @"ANDRE", 
                        @"ANDREA", 
                        @"ANDREAS", 
                        @"ANDRES", 
                        @"ANDREW", 
                        @"ANDY", 
                        @"ANGEL", 
                        @"ANGELO", 
                        @"ANIBAL", 
                        @"ANTHONY", 
                        @"ANTIONE", 
                        @"ANTOINE", 
                        @"ANTON", 
                        @"ANTONE", 
                        @"ANTONIA", 
                        @"ANTONIO", 
                        @"ANTONY", 
                        @"ANTWAN", 
                        @"ARCHIE", 
                        @"ARDEN", 
                        @"ARIEL", 
                        @"ARLEN", 
                        @"ARLIE", 
                        @"ARMAND", 
                        @"ARMANDO", 
                        @"ARNOLD", 
                        @"ARNOLDO", 
                        @"ARNULFO", 
                        @"ARON", 
                        @"ARRON", 
                        @"ART", 
                        @"ARTHUR", 
                        @"ARTURO", 
                        @"ASA", 
                        @"ASHLEY", 
                        @"AUBREY", 
                        @"AUGUST", 
                        @"AUGUSTINE", 
                        @"AUGUSTUS", 
                        @"AURELIO", 
                        @"AUSTIN", 
                        @"AVERY", 
                        @"BARNEY", 
                        @"BARRETT", 
                        @"BARRY", 
                        @"BART", 
                        @"BARTON", 
                        @"BASIL", 
                        @"BEAU", 
                        @"BEN", 
                        @"BENEDICT", 
                        @"BENITO", 
                        @"BENJAMIN", 
                        @"BENNETT", 
                        @"BENNIE", 
                        @"BENNY", 
                        @"BENTON", 
                        @"BERNARD", 
                        @"BERNARDO", 
                        @"BERNIE", 
                        @"BERRY", 
                        @"BERT", 
                        @"BERTRAM", 
                        @"BILL", 
                        @"BILLIE", 
                        @"BILLY", 
                        @"BLAINE", 
                        @"BLAIR", 
                        @"BLAKE", 
                        @"BO", 
                        @"BOB", 
                        @"BOBBIE", 
                        @"BOBBY", 
                        @"BOOKER", 
                        @"BORIS", 
                        @"BOYCE", 
                        @"BOYD", 
                        @"BRAD", 
                        @"BRADFORD", 
                        @"BRADLEY", 
                        @"BRADLY", 
                        @"BRADY", 
                        @"BRAIN", 
                        @"BRANDEN", 
                        @"BRANDON", 
                        @"BRANT", 
                        @"BRENDAN", 
                        @"BRENDON", 
                        @"BRENT", 
                        @"BRENTON", 
                        @"BRET", 
                        @"BRETT", 
                        @"BRIAN", 
                        @"BRICE", 
                        @"BRITT", 
                        @"BROCK", 
                        @"BRODERICK", 
                        @"BROOKS", 
                        @"BRUCE", 
                        @"BRUNO", 
                        @"BRYAN", 
                        @"BRYANT", 
                        @"BRYCE", 
                        @"BRYON", 
                        @"BUCK", 
                        @"BUD", 
                        @"BUDDY", 
                        @"BUFORD", 
                        @"BURL", 
                        @"BURT", 
                        @"BURTON", 
                        @"BUSTER", 
                        @"BYRON", 
                        @"CALEB", 
                        @"CALVIN", 
                        @"CAMERON", 
                        @"CAREY", 
                        @"CARL", 
                        @"CARLO", 
                        @"CARLOS", 
                        @"CARLTON", 
                        @"CARMELO", 
                        @"CARMEN", 
                        @"CARMINE", 
                        @"CAROL", 
                        @"CARROL", 
                        @"CARROLL", 
                        @"CARSON", 
                        @"CARTER", 
                        @"CARY", 
                        @"CASEY", 
                        @"CECIL", 
                        @"CEDRIC", 
                        @"CEDRICK", 
                        @"CESAR", 
                        @"CHAD", 
                        @"CHADWICK", 
                        @"CHANCE", 
                        @"CHANG", 
                        @"CHARLES", 
                        @"CHARLEY", 
                        @"CHARLIE", 
                        @"CHAS", 
                        @"CHASE", 
                        @"CHAUNCEY", 
                        @"CHESTER", 
                        @"CHET", 
                        @"CHI", 
                        @"CHONG", 
                        @"CHRIS", 
                        @"CHRISTIAN", 
                        @"CHRISTOPER", 
                        @"CHRISTOPHER", 
                        @"CHUCK", 
                        @"CHUNG", 
                        @"CLAIR", 
                        @"CLARENCE", 
                        @"CLARK", 
                        @"CLAUD", 
                        @"CLAUDE", 
                        @"CLAUDIO", 
                        @"CLAY", 
                        @"CLAYTON", 
                        @"CLEMENT", 
                        @"CLEMENTE", 
                        @"CLEO", 
                        @"CLETUS", 
                        @"CLEVELAND", 
                        @"CLIFF", 
                        @"CLIFFORD", 
                        @"CLIFTON", 
                        @"CLINT", 
                        @"CLINTON", 
                        @"CLYDE", 
                        @"CODY", 
                        @"COLBY", 
                        @"COLE", 
                        @"COLEMAN", 
                        @"COLIN", 
                        @"COLLIN", 
                        @"COLTON", 
                        @"COLUMBUS", 
                        @"CONNIE", 
                        @"CONRAD", 
                        @"CORDELL", 
                        @"COREY", 
                        @"CORNELIUS", 
                        @"CORNELL", 
                        @"CORTEZ", 
                        @"CORY", 
                        @"COURTNEY", 
                        @"COY", 
                        @"CRAIG", 
                        @"CRISTOBAL", 
                        @"CRISTOPHER", 
                        @"CRUZ", 
                        @"CURT", 
                        @"CURTIS", 
                        @"CYRIL", 
                        @"CYRUS", 
                        @"DALE", 
                        @"DALLAS", 
                        @"DALTON", 
                        @"DAMIAN", 
                        @"DAMIEN", 
                        @"DAMION", 
                        @"DAMON", 
                        @"DAN", 
                        @"DANA", 
                        @"DANE", 
                        @"DANIAL", 
                        @"DANIEL", 
                        @"DANILO", 
                        @"DANNIE", 
                        @"DANNY", 
                        @"DANTE", 
                        @"DARELL", 
                        @"DAREN", 
                        @"DARIN", 
                        @"DARIO", 
                        @"DARIUS", 
                        @"DARNELL", 
                        @"DARON", 
                        @"DARREL", 
                        @"DARRELL", 
                        @"DARREN", 
                        @"DARRICK", 
                        @"DARRIN", 
                        @"DARRON", 
                        @"DARRYL", 
                        @"DARWIN", 
                        @"DARYL", 
                        @"DAVE", 
                        @"DAVID", 
                        @"DAVIS", 
                        @"DEAN", 
                        @"DEANDRE", 
                        @"DEANGELO", 
                        @"DEE", 
                        @"DEL", 
                        @"DELBERT", 
                        @"DELMAR", 
                        @"DELMER", 
                        @"DEMARCUS", 
                        @"DEMETRIUS", 
                        @"DENIS", 
                        @"DENNIS", 
                        @"DENNY", 
                        @"DENVER", 
                        @"DEON", 
                        @"DEREK", 
                        @"DERICK", 
                        @"DERRICK", 
                        @"DESHAWN", 
                        @"DESMOND", 
                        @"DEVIN", 
                        @"DEVON", 
                        @"DEWAYNE", 
                        @"DEWEY", 
                        @"DEWITT", 
                        @"DEXTER", 
                        @"DICK", 
                        @"DIEGO", 
                        @"DILLON", 
                        @"DINO", 
                        @"DION", 
                        @"DIRK", 
                        @"DOMENIC", 
                        @"DOMINGO", 
                        @"DOMINIC", 
                        @"DOMINICK", 
                        @"DOMINIQUE", 
                        @"DON", 
                        @"DONALD", 
                        @"DONG", 
                        @"DONN", 
                        @"DONNELL", 
                        @"DONNIE", 
                        @"DONNY", 
                        @"DONOVAN", 
                        @"DONTE", 
                        @"DORIAN", 
                        @"DORSEY", 
                        @"DOUG", 
                        @"DOUGLAS", 
                        @"DOUGLASS", 
                        @"DOYLE", 
                        @"DREW", 
                        @"DUANE", 
                        @"DUDLEY", 
                        @"DUNCAN", 
                        @"DUSTIN", 
                        @"DUSTY", 
                        @"DWAIN", 
                        @"DWAYNE", 
                        @"DWIGHT", 
                        @"DYLAN", 
                        @"EARL", 
                        @"EARLE", 
                        @"EARNEST", 
                        @"ED", 
                        @"EDDIE", 
                        @"EDDY", 
                        @"EDGAR", 
                        @"EDGARDO", 
                        @"EDISON", 
                        @"EDMOND", 
                        @"EDMUND", 
                        @"EDMUNDO", 
                        @"EDUARDO", 
                        @"EDWARD", 
                        @"EDWARDO", 
                        @"EDWIN", 
                        @"EFRAIN", 
                        @"EFREN", 
                        @"ELBERT", 
                        @"ELDEN", 
                        @"ELDON", 
                        @"ELDRIDGE", 
                        @"ELI", 
                        @"ELIAS", 
                        @"ELIJAH", 
                        @"ELISEO", 
                        @"ELISHA", 
                        @"ELLIOT", 
                        @"ELLIOTT", 
                        @"ELLIS", 
                        @"ELLSWORTH", 
                        @"ELMER", 
                        @"ELMO", 
                        @"ELOY", 
                        @"ELROY", 
                        @"ELTON", 
                        @"ELVIN", 
                        @"ELVIS", 
                        @"ELWOOD", 
                        @"EMANUEL", 
                        @"EMERSON", 
                        @"EMERY", 
                        @"EMIL", 
                        @"EMILE", 
                        @"EMILIO", 
                        @"EMMANUEL", 
                        @"EMMETT", 
                        @"EMMITT", 
                        @"EMORY", 
                        @"ENOCH", 
                        @"ENRIQUE", 
                        @"ERASMO", 
                        @"ERIC", 
                        @"ERICH", 
                        @"ERICK", 
                        @"ERIK", 
                        @"ERIN", 
                        @"ERNEST", 
                        @"ERNESTO", 
                        @"ERNIE", 
                        @"ERROL", 
                        @"ERVIN", 
                        @"ERWIN", 
                        @"ESTEBAN", 
                        @"ETHAN", 
                        @"EUGENE", 
                        @"EUGENIO", 
                        @"EUSEBIO", 
                        @"EVAN", 
                        @"EVERETT", 
                        @"EVERETTE", 
                        @"EZEKIEL", 
                        @"EZEQUIEL", 
                        @"EZRA", 
                        @"FABIAN", 
                        @"FAUSTINO", 
                        @"FAUSTO", 
                        @"FEDERICO", 
                        @"FELIPE", 
                        @"FELIX", 
                        @"FELTON", 
                        @"FERDINAND", 
                        @"FERMIN", 
                        @"FERNANDO", 
                        @"FIDEL", 
                        @"FILIBERTO", 
                        @"FLETCHER", 
                        @"FLORENCIO", 
                        @"FLORENTINO", 
                        @"FLOYD", 
                        @"FOREST", 
                        @"FORREST", 
                        @"FOSTER", 
                        @"FRANCES", 
                        @"FRANCESCO", 
                        @"FRANCIS", 
                        @"FRANCISCO", 
                        @"FRANK", 
                        @"FRANKIE", 
                        @"FRANKLIN", 
                        @"FRANKLYN", 
                        @"FRED", 
                        @"FREDDIE", 
                        @"FREDDY", 
                        @"FREDERIC", 
                        @"FREDERICK", 
                        @"FREDRIC", 
                        @"FREDRICK", 
                        @"FREEMAN", 
                        @"FRITZ", 
                        @"GABRIEL", 
                        @"GAIL", 
                        @"GALE", 
                        @"GALEN", 
                        @"GARFIELD", 
                        @"GARLAND", 
                        @"GARRET", 
                        @"GARRETT", 
                        @"GARRY", 
                        @"GARTH", 
                        @"GARY", 
                        @"GASTON", 
                        @"GAVIN", 
                        @"GAYLE", 
                        @"GAYLORD", 
                        @"GENARO", 
                        @"GENE", 
                        @"GEOFFREY", 
                        @"GEORGE", 
                        @"GERALD", 
                        @"GERALDO", 
                        @"GERARD", 
                        @"GERARDO", 
                        @"GERMAN", 
                        @"GERRY", 
                        @"GIL", 
                        @"GILBERT", 
                        @"GILBERTO", 
                        @"GINO", 
                        @"GIOVANNI", 
                        @"GIUSEPPE", 
                        @"GLEN", 
                        @"GLENN", 
                        @"GONZALO", 
                        @"GORDON", 
                        @"GRADY", 
                        @"GRAHAM", 
                        @"GRAIG", 
                        @"GRANT", 
                        @"GRANVILLE", 
                        @"GREG", 
                        @"GREGG", 
                        @"GREGORIO", 
                        @"GREGORY", 
                        @"GROVER", 
                        @"GUADALUPE", 
                        @"GUILLERMO", 
                        @"GUS", 
                        @"GUSTAVO", 
                        @"GUY", 
                        @"HAI", 
                        @"HAL", 
                        @"HANK", 
                        @"HANS", 
                        @"HARLAN", 
                        @"HARLAND", 
                        @"HARLEY", 
                        @"HAROLD", 
                        @"HARRIS", 
                        @"HARRISON", 
                        @"HARRY", 
                        @"HARVEY", 
                        @"HASSAN", 
                        @"HAYDEN", 
                        @"HAYWOOD", 
                        @"HEATH", 
                        @"HECTOR", 
                        @"HENRY", 
                        @"HERB", 
                        @"HERBERT", 
                        @"HERIBERTO", 
                        @"HERMAN", 
                        @"HERSCHEL", 
                        @"HERSHEL", 
                        @"HILARIO", 
                        @"HILTON", 
                        @"HIPOLITO", 
                        @"HIRAM", 
                        @"HOBERT", 
                        @"HOLLIS", 
                        @"HOMER", 
                        @"HONG", 
                        @"HORACE", 
                        @"HORACIO", 
                        @"HOSEA", 
                        @"HOUSTON", 
                        @"HOWARD", 
                        @"HOYT", 
                        @"HUBERT", 
                        @"HUEY", 
                        @"HUGH", 
                        @"HUGO", 
                        @"HUMBERTO", 
                        @"HUNG", 
                        @"HUNTER", 
                        @"HYMAN", 
                        @"IAN", 
                        @"IGNACIO", 
                        @"IKE", 
                        @"IRA", 
                        @"IRVIN", 
                        @"IRVING", 
                        @"IRWIN", 
                        @"ISAAC", 
                        @"ISAIAH", 
                        @"ISAIAS", 
                        @"ISIAH", 
                        @"ISIDRO", 
                        @"ISMAEL", 
                        @"ISRAEL", 
                        @"ISREAL", 
                        @"ISSAC", 
                        @"IVAN", 
                        @"IVORY", 
                        @"JACINTO", 
                        @"JACK", 
                        @"JACKIE", 
                        @"JACKSON", 
                        @"JACOB", 
                        @"JACQUES", 
                        @"JAE", 
                        @"JAIME", 
                        @"JAKE", 
                        @"JAMAAL", 
                        @"JAMAL", 
                        @"JAMAR", 
                        @"JAME", 
                        @"JAMEL", 
                        @"JAMES", 
                        @"JAMEY", 
                        @"JAMIE", 
                        @"JAMISON", 
                        @"JAN", 
                        @"JARED", 
                        @"JAROD", 
                        @"JARRED", 
                        @"JARRETT", 
                        @"JARROD", 
                        @"JARVIS", 
                        @"JASON", 
                        @"JASPER", 
                        @"JAVIER", 
                        @"JAY", 
                        @"JAYSON", 
                        @"JC", 
                        @"JEAN", 
                        @"JED", 
                        @"JEFF", 
                        @"JEFFEREY", 
                        @"JEFFERSON", 
                        @"JEFFERY", 
                        @"JEFFREY", 
                        @"JEFFRY", 
                        @"JERALD", 
                        @"JERAMY", 
                        @"JERE", 
                        @"JEREMIAH", 
                        @"JEREMY", 
                        @"JERMAINE", 
                        @"JEROLD", 
                        @"JEROME", 
                        @"JEROMY", 
                        @"JERRELL", 
                        @"JERROD", 
                        @"JERROLD", 
                        @"JERRY", 
                        @"JESS", 
                        @"JESSE", 
                        @"JESSIE", 
                        @"JESUS", 
                        @"JEWEL", 
                        @"JEWELL", 
                        @"JIM", 
                        @"JIMMIE", 
                        @"JIMMY", 
                        @"JOAN", 
                        @"JOAQUIN", 
                        @"JODY", 
                        @"JOE", 
                        @"JOEL", 
                        @"JOESPH", 
                        @"JOEY", 
                        @"JOHN", 
                        @"JOHNATHAN", 
                        @"JOHNATHON", 
                        @"JOHNIE", 
                        @"JOHNNIE", 
                        @"JOHNNY", 
                        @"JOHNSON", 
                        @"JON", 
                        @"JONAH", 
                        @"JONAS", 
                        @"JONATHAN", 
                        @"JONATHON", 
                        @"JORDAN", 
                        @"JORDON", 
                        @"JORGE", 
                        @"JOSE", 
                        @"JOSEF", 
                        @"JOSEPH", 
                        @"JOSH", 
                        @"JOSHUA", 
                        @"JOSIAH", 
                        @"JOSPEH", 
                        @"JOSUE", 
                        @"JUAN", 
                        @"JUDE", 
                        @"JUDSON", 
                        @"JULES", 
                        @"JULIAN", 
                        @"JULIO", 
                        @"JULIUS", 
                        @"JUNIOR", 
                        @"JUSTIN", 
                        @"KAREEM", 
                        @"KARL", 
                        @"KASEY", 
                        @"KEENAN", 
                        @"KEITH", 
                        @"KELLEY", 
                        @"KELLY", 
                        @"KELVIN", 
                        @"KEN", 
                        @"KENDALL", 
                        @"KENDRICK", 
                        @"KENETH", 
                        @"KENNETH", 
                        @"KENNITH", 
                        @"KENNY", 
                        @"KENT", 
                        @"KENTON", 
                        @"KERMIT", 
                        @"KERRY", 
                        @"KEVEN", 
                        @"KEVIN", 
                        @"KIETH", 
                        @"KIM", 
                        @"KING", 
                        @"KIP", 
                        @"KIRBY", 
                        @"KIRK", 
                        @"KOREY", 
                        @"KORY", 
                        @"KRAIG", 
                        @"KRIS", 
                        @"KRISTOFER", 
                        @"KRISTOPHER", 
                        @"KURT", 
                        @"KURTIS", 
                        @"KYLE", 
                        @"LACY", 
                        @"LAMAR", 
                        @"LAMONT", 
                        @"LANCE", 
                        @"LANDON", 
                        @"LANE", 
                        @"LANNY", 
                        @"LARRY", 
                        @"LAUREN", 
                        @"LAURENCE", 
                        @"LAVERN", 
                        @"LAVERNE", 
                        @"LAWERENCE", 
                        @"LAWRENCE", 
                        @"LAZARO", 
                        @"LEANDRO", 
                        @"LEE", 
                        @"LEIF", 
                        @"LEIGH", 
                        @"LELAND", 
                        @"LEMUEL", 
                        @"LEN", 
                        @"LENARD", 
                        @"LENNY", 
                        @"LEO", 
                        @"LEON", 
                        @"LEONARD", 
                        @"LEONARDO", 
                        @"LEONEL", 
                        @"LEOPOLDO", 
                        @"LEROY", 
                        @"LES", 
                        @"LESLEY", 
                        @"LESLIE", 
                        @"LESTER", 
                        @"LEVI", 
                        @"LEWIS", 
                        @"LINCOLN", 
                        @"LINDSAY", 
                        @"LINDSEY", 
                        @"LINO", 
                        @"LINWOOD", 
                        @"LIONEL", 
                        @"LLOYD", 
                        @"LOGAN", 
                        @"LON", 
                        @"LONG", 
                        @"LONNIE", 
                        @"LONNY", 
                        @"LOREN", 
                        @"LORENZO", 
                        @"LOU", 
                        @"LOUIE", 
                        @"LOUIS", 
                        @"LOWELL", 
                        @"LOYD", 
                        @"LUCAS", 
                        @"LUCIANO", 
                        @"LUCIEN", 
                        @"LUCIO", 
                        @"LUCIUS", 
                        @"LUIGI", 
                        @"LUIS", 
                        @"LUKE", 
                        @"LUPE", 
                        @"LUTHER", 
                        @"LYLE", 
                        @"LYMAN", 
                        @"LYNDON", 
                        @"LYNN", 
                        @"LYNWOOD", 
                        @"MAC", 
                        @"MACK", 
                        @"MAJOR", 
                        @"MALCOLM", 
                        @"MALCOM", 
                        @"MALIK", 
                        @"MAN", 
                        @"MANUAL", 
                        @"MANUEL", 
                        @"MARC", 
                        @"MARCEL", 
                        @"MARCELINO", 
                        @"MARCELLUS", 
                        @"MARCELO", 
                        @"MARCO", 
                        @"MARCOS", 
                        @"MARCUS", 
                        @"MARGARITO", 
                        @"MARIA", 
                        @"MARIANO", 
                        @"MARIO", 
                        @"MARION", 
                        @"MARK", 
                        @"MARKUS", 
                        @"MARLIN", 
                        @"MARLON", 
                        @"MARQUIS", 
                        @"MARSHALL", 
                        @"MARTIN", 
                        @"MARTY", 
                        @"MARVIN", 
                        @"MARY", 
                        @"MASON", 
                        @"MATHEW", 
                        @"MATT", 
                        @"MATTHEW", 
                        @"MAURICE", 
                        @"MAURICIO", 
                        @"MAURO", 
                        @"MAX", 
                        @"MAXIMO", 
                        @"MAXWELL", 
                        @"MAYNARD", 
                        @"MCKINLEY", 
                        @"MEL", 
                        @"MELVIN", 
                        @"MERLE", 
                        @"MERLIN", 
                        @"MERRILL", 
                        @"MERVIN", 
                        @"MICAH", 
                        @"MICHAEL", 
                        @"MICHAL", 
                        @"MICHALE", 
                        @"MICHEAL", 
                        @"MICHEL", 
                        @"MICKEY", 
                        @"MIGUEL", 
                        @"MIKE", 
                        @"MIKEL", 
                        @"MILAN", 
                        @"MILES", 
                        @"MILFORD", 
                        @"MILLARD", 
                        @"MILO", 
                        @"MILTON", 
                        @"MINH", 
                        @"MIQUEL", 
                        @"MITCH", 
                        @"MITCHEL", 
                        @"MITCHELL", 
                        @"MODESTO", 
                        @"MOHAMED", 
                        @"MOHAMMAD", 
                        @"MOHAMMED", 
                        @"MOISES", 
                        @"MONROE", 
                        @"MONTE", 
                        @"MONTY", 
                        @"MORGAN", 
                        @"MORRIS", 
                        @"MORTON", 
                        @"MOSE", 
                        @"MOSES", 
                        @"MOSHE", 
                        @"MURRAY", 
                        @"MYLES", 
                        @"MYRON", 
                        @"NAPOLEON", 
                        @"NATHAN", 
                        @"NATHANAEL", 
                        @"NATHANIAL", 
                        @"NATHANIEL", 
                        @"NEAL", 
                        @"NED", 
                        @"NEIL", 
                        @"NELSON", 
                        @"NESTOR", 
                        @"NEVILLE", 
                        @"NEWTON", 
                        @"NICHOLAS", 
                        @"NICK", 
                        @"NICKOLAS", 
                        @"NICKY", 
                        @"NICOLAS", 
                        @"NIGEL", 
                        @"NOAH", 
                        @"NOBLE", 
                        @"NOE", 
                        @"NOEL", 
                        @"NOLAN", 
                        @"NORBERT", 
                        @"NORBERTO", 
                        @"NORMAN", 
                        @"NORMAND", 
                        @"NORRIS", 
                        @"NUMBERS", 
                        @"OCTAVIO", 
                        @"ODELL", 
                        @"ODIS", 
                        @"OLEN", 
                        @"OLIN", 
                        @"OLIVER", 
                        @"OLLIE", 
                        @"OMAR", 
                        @"OMER", 
                        @"OREN", 
                        @"ORLANDO", 
                        @"ORVAL", 
                        @"ORVILLE", 
                        @"OSCAR", 
                        @"OSVALDO", 
                        @"OSWALDO", 
                        @"OTHA", 
                        @"OTIS", 
                        @"OTTO", 
                        @"OWEN", 
                        @"PABLO", 
                        @"PALMER", 
                        @"PARIS", 
                        @"PARKER", 
                        @"PASQUALE", 
                        @"PAT", 
                        @"PATRICIA", 
                        @"PATRICK", 
                        @"PAUL", 
                        @"PEDRO", 
                        @"PERCY", 
                        @"PERRY", 
                        @"PETE", 
                        @"PETER", 
                        @"PHIL", 
                        @"PHILIP", 
                        @"PHILLIP", 
                        @"PIERRE", 
                        @"PORFIRIO", 
                        @"PORTER", 
                        @"PRESTON", 
                        @"PRINCE", 
                        @"QUENTIN", 
                        @"QUINCY", 
                        @"QUINN", 
                        @"QUINTIN", 
                        @"QUINTON", 
                        @"RAFAEL", 
                        @"RALEIGH", 
                        @"RALPH", 
                        @"RAMIRO", 
                        @"RAMON", 
                        @"RANDAL", 
                        @"RANDALL", 
                        @"RANDELL", 
                        @"RANDOLPH", 
                        @"RANDY", 
                        @"RAPHAEL", 
                        @"RASHAD", 
                        @"RAUL", 
                        @"RAY", 
                        @"RAYFORD", 
                        @"RAYMON", 
                        @"RAYMOND", 
                        @"RAYMUNDO", 
                        @"REED", 
                        @"REFUGIO", 
                        @"REGGIE", 
                        @"REGINALD", 
                        @"REID", 
                        @"REINALDO", 
                        @"RENALDO", 
                        @"RENATO", 
                        @"RENE", 
                        @"REUBEN", 
                        @"REX", 
                        @"REY", 
                        @"REYES", 
                        @"REYNALDO", 
                        @"RHETT", 
                        @"RICARDO", 
                        @"RICH", 
                        @"RICHARD", 
                        @"RICHIE", 
                        @"RICK", 
                        @"RICKEY", 
                        @"RICKIE", 
                        @"RICKY", 
                        @"RICO", 
                        @"RIGOBERTO", 
                        @"RILEY", 
                        @"ROB", 
                        @"ROBBIE", 
                        @"ROBBY", 
                        @"ROBERT", 
                        @"ROBERTO", 
                        @"ROBIN", 
                        @"ROBT", 
                        @"ROCCO", 
                        @"ROCKY", 
                        @"ROD", 
                        @"RODERICK", 
                        @"RODGER", 
                        @"RODNEY", 
                        @"RODOLFO", 
                        @"RODRICK", 
                        @"RODRIGO", 
                        @"ROGELIO", 
                        @"ROGER", 
                        @"ROLAND", 
                        @"ROLANDO", 
                        @"ROLF", 
                        @"ROLLAND", 
                        @"ROMAN", 
                        @"ROMEO", 
                        @"RON", 
                        @"RONALD", 
                        @"RONNIE", 
                        @"RONNY", 
                        @"ROOSEVELT", 
                        @"RORY", 
                        @"ROSARIO", 
                        @"ROSCOE", 
                        @"ROSENDO", 
                        @"ROSS", 
                        @"ROY", 
                        @"ROYAL", 
                        @"ROYCE", 
                        @"RUBEN", 
                        @"RUBIN", 
                        @"RUDOLF", 
                        @"RUDOLPH", 
                        @"RUDY", 
                        @"RUEBEN", 
                        @"RUFUS", 
                        @"RUPERT", 
                        @"RUSS", 
                        @"RUSSEL", 
                        @"RUSSELL", 
                        @"RUSTY", 
                        @"RYAN", 
                        @"SAL", 
                        @"SALVADOR", 
                        @"SALVATORE", 
                        @"SAM", 
                        @"SAMMIE", 
                        @"SAMMY", 
                        @"SAMUAL", 
                        @"SAMUEL", 
                        @"SANDY", 
                        @"SANFORD", 
                        @"SANG", 
                        @"SANTIAGO", 
                        @"SANTO", 
                        @"SANTOS", 
                        @"SAUL", 
                        @"SCOT", 
                        @"SCOTT", 
                        @"SCOTTIE", 
                        @"SCOTTY", 
                        @"SEAN", 
                        @"SEBASTIAN", 
                        @"SERGIO", 
                        @"SETH", 
                        @"SEYMOUR", 
                        @"SHAD", 
                        @"SHANE", 
                        @"SHANNON", 
                        @"SHAUN", 
                        @"SHAWN", 
                        @"SHAYNE", 
                        @"SHELBY", 
                        @"SHELDON", 
                        @"SHELTON", 
                        @"SHERMAN", 
                        @"SHERWOOD", 
                        @"SHIRLEY", 
                        @"SHON", 
                        @"SID", 
                        @"SIDNEY", 
                        @"SILAS", 
                        @"SIMON", 
                        @"SOL", 
                        @"SOLOMON", 
                        @"SON", 
                        @"SONNY", 
                        @"SPENCER", 
                        @"STACEY", 
                        @"STACY", 
                        @"STAN", 
                        @"STANFORD", 
                        @"STANLEY", 
                        @"STANTON", 
                        @"STEFAN", 
                        @"STEPHAN", 
                        @"STEPHEN", 
                        @"STERLING", 
                        @"STEVE", 
                        @"STEVEN", 
                        @"STEVIE", 
                        @"STEWART", 
                        @"STUART", 
                        @"SUNG", 
                        @"SYDNEY", 
                        @"SYLVESTER", 
                        @"TAD", 
                        @"TANNER", 
                        @"TAYLOR", 
                        @"TED", 
                        @"TEDDY", 
                        @"TEODORO", 
                        @"TERENCE", 
                        @"TERRANCE", 
                        @"TERRELL", 
                        @"TERRENCE", 
                        @"TERRY", 
                        @"THAD", 
                        @"THADDEUS", 
                        @"THANH", 
                        @"THEO", 
                        @"THEODORE", 
                        @"THERON", 
                        @"THOMAS", 
                        @"THURMAN", 
                        @"TIM", 
                        @"TIMMY", 
                        @"TIMOTHY", 
                        @"TITUS", 
                        @"TOBIAS", 
                        @"TOBY", 
                        @"TOD", 
                        @"TODD", 
                        @"TOM", 
                        @"TOMAS", 
                        @"TOMMIE", 
                        @"TOMMY", 
                        @"TONEY", 
                        @"TONY", 
                        @"TORY", 
                        @"TRACEY", 
                        @"TRACY", 
                        @"TRAVIS", 
                        @"TRENT", 
                        @"TRENTON", 
                        @"TREVOR", 
                        @"TREY", 
                        @"TRINIDAD", 
                        @"TRISTAN", 
                        @"TROY", 
                        @"TRUMAN", 
                        @"TUAN", 
                        @"TY", 
                        @"TYLER", 
                        @"TYREE", 
                        @"TYRELL", 
                        @"TYRON", 
                        @"TYRONE", 
                        @"TYSON", 
                        @"ULYSSES", 
                        @"VAL", 
                        @"VALENTIN", 
                        @"VALENTINE", 
                        @"VAN", 
                        @"VANCE", 
                        @"VAUGHN", 
                        @"VERN", 
                        @"VERNON", 
                        @"VICENTE", 
                        @"VICTOR", 
                        @"VINCE", 
                        @"VINCENT", 
                        @"VINCENZO", 
                        @"VIRGIL", 
                        @"VIRGILIO", 
                        @"VITO", 
                        @"VON", 
                        @"WADE", 
                        @"WALDO", 
                        @"WALKER", 
                        @"WALLACE", 
                        @"WALLY", 
                        @"WALTER", 
                        @"WALTON", 
                        @"WARD", 
                        @"WARNER", 
                        @"WARREN", 
                        @"WAYLON", 
                        @"WAYNE", 
                        @"WELDON", 
                        @"WENDELL", 
                        @"WERNER", 
                        @"WES", 
                        @"WESLEY", 
                        @"WESTON", 
                        @"WHITNEY", 
                        @"WILBER", 
                        @"WILBERT", 
                        @"WILBUR", 
                        @"WILBURN", 
                        @"WILEY", 
                        @"WILFORD", 
                        @"WILFRED", 
                        @"WILFREDO", 
                        @"WILL", 
                        @"WILLARD", 
                        @"WILLIAM", 
                        @"WILLIAMS", 
                        @"WILLIAN", 
                        @"WILLIE", 
                        @"WILLIS", 
                        @"WILLY", 
                        @"WILMER", 
                        @"WILSON", 
                        @"WILTON", 
                        @"WINFORD", 
                        @"WINFRED", 
                        @"WINSTON", 
                        @"WM", 
                        @"WOODROW", 
                        @"WYATT", 
                        @"XAVIER", 
                        @"YONG", 
                        @"YOUNG", 
                        @"ZACHARIAH", 
                        @"ZACHARY", 
                        @"ZACHERY", 
                        @"ZACK", 
                        @"ZACKARY", 
                        @"ZANE", nil];
    
    NSMutableArray* a = [NSMutableArray arrayWithCapacity:1];
    
    for (int i = 0; i < 1000; i++) {
        Personne* p = [[Personne alloc] init];
        int idx = rand() % prenoms.count;
        NSMutableString* str = [NSMutableString stringWithCapacity:1];
        [str appendString:[prenoms objectAtIndex:idx]];
        [str appendString:@" "];
        p.prenom = [NSString stringWithString:str];
        
        idx = rand() % prenoms.count;
        str = [NSMutableString stringWithCapacity:1];
        [str appendString:[prenoms objectAtIndex:idx]];
        [str appendString:@"nn"];
        p.nom = [NSString stringWithString:str];
        
        str = [NSMutableString stringWithCapacity:1];
        NSMutableString* str2 = [NSMutableString stringWithCapacity:1];
        for (int j = 0; j < 10; j++) {
            if (j > 0 && (j & 1) == 0) {
                [str appendString:@" "];
            }
            [str appendFormat:@"%01d", rand() % 10];
            [str2 appendFormat:@"%01d", rand() % 10];
        }
        p.telephone = [NSString stringWithString:str];
        p.phoneDigits = [NSString stringWithString:str2];
        [a addObject:p];
        [p release];
    }
    
    NSArray* objects = [a sortedArrayUsingSelector:@selector(compare:)];
    data = [[self partitionObjects:objects collationStringSelector:@selector(nom)] retain];
    
    return self;
}


-(NSArray *)partitionObjects:(NSArray *)array collationStringSelector:(SEL)selector

{
    CollateAndSearch *collation = [CollateAndSearch currentCollation];
    
    NSInteger sectionCount = [[collation sectionTitles] count]; //section count is take from sectionTitles and not sectionIndexTitles
    NSMutableArray *unsortedSections = [NSMutableArray arrayWithCapacity:sectionCount];
    
    //create an array to hold the data for each section
    for(int i = 0; i < sectionCount; i++)
    {
        [unsortedSections addObject:[NSMutableArray array]];
    }
    
    //put each object into a section
    for (id object in array)
    {
        NSInteger index = [collation sectionForObject:object collationStringSelector:selector];
        [[unsortedSections objectAtIndex:index] addObject:object];
    }
    
    NSMutableArray *sections = [NSMutableArray arrayWithCapacity:sectionCount];
    //sort each section
    for (NSMutableArray *section in unsortedSections)
    {
        [sections addObject:[collation sortedArrayFromArray:section collationStringSelector:selector]];
    }
    
    return sections;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    static NSString *CellId = @"RubriqueCell";
    
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:CellId];
    if (cell == nil) {
        cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:CellId];
    }
    NSArray* dataSource;
    if (filtered) {
        dataSource = filteredData;
    } else {
        dataSource = [data objectAtIndex:indexPath.section];
    }
    Personne* p = [dataSource objectAtIndex:indexPath.row];
    if (filtered) {
        // TODO...
    }
    cell.textLabel.font = [UIFont fontWithName:@"Helvetica" size:15];
    if (phoneShown) {
        cell.textLabel.text = p.phoneDigits;
        cell.detailTextLabel.text = [p.prenom stringByAppendingFormat:@" %@", p.nom];
    } else {
        cell.detailTextLabel.text = nil;
        cell.textLabel.text = [p.prenom stringByAppendingFormat:@" %@", p.nom];
    }
    return cell;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
    if (filtered) {
        return [filteredData count];
    } else {
        return [[data objectAtIndex:section] count];
    }
}


- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    if (filtered) {
        return 1;
    } else {
        return [[[CollateAndSearch currentCollation] sectionTitles] count];
    }
}

- (NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section
{
    if (filtered) {
        return nil;
    } else {
        return [[[CollateAndSearch currentCollation] sectionTitles] objectAtIndex:section];
    }
}

- (NSArray *)sectionIndexTitlesForTableView:(UITableView *)tableView
{
    if (!indexShown) {
        return nil;
    } else {
        return [[CollateAndSearch currentCollation] sectionIndexTitles];
    }
}

- (NSInteger)tableView:(UITableView *)tableView sectionForSectionIndexTitle:(NSString *)title atIndex:(NSInteger)index
{
    if (filtered) {
        return NSNotFound;
    } else {
        NSInteger section = [[CollateAndSearch currentCollation] sectionForSectionIndexTitleAtIndex:index];
        if(section == NSNotFound) { 
            [tableView setContentOffset:CGPointMake(0,0)];
        }
        return section;
    }
}

- (void) filterStartingWith:(NSArray*)source to:(NSMutableArray*)result with:(NSString*)searchTerm
{
    for (Personne* p in source) {
        if ([p.nom hasPrefix:searchTerm] || [p.prenom hasPrefix:searchTerm]) {
            [result addObject:p];
        }
    }
}

- (void) filterContainsAfterFirstChar:(NSArray*)source to:(NSMutableArray*)result with:(NSString*)searchTerm
{
    for (Personne* p in source) {
        if ([[p.nom substringFromIndex:1] rangeOfString:searchTerm].location != NSNotFound
            || [[p.prenom substringFromIndex:1] rangeOfString:searchTerm].location != NSNotFound) {
            [result addObject:p];
        }
    }
}


- (void) filterTelephone:(NSArray*)source to:(NSMutableArray*)result with:(NSString*)searchTerm
{
    for (Personne* p in source) {
        if ([p.phoneDigits rangeOfString:searchTerm].location != NSNotFound) {
            [result addObject:p];
        }
    }
}

- (void) setFilter:(NSString*)f
{
    NSString* searchTerm = [f uppercaseString];
    if (f == nil || f.length == 0) {
        self.filteredData = nil;
        phoneShown = NO;
    } else {
        NSCharacterSet* numberCharSet = [NSCharacterSet characterSetWithCharactersInString:@"0123456789 +()"];
        BOOL phoneSearch = ([searchTerm rangeOfCharacterFromSet:numberCharSet].length > 0);
        phoneShown = phoneSearch;

        NSMutableArray* result = [NSMutableArray arrayWithCapacity:1];
        if (1 || filter == nil || [searchTerm rangeOfString:filter].location == NSNotFound) {
            if (phoneShown) {
                for (NSArray* array in data) {
                    [self filterTelephone:array to:result with:searchTerm];
                }
            } else {
                for (NSArray* array in data) {
                    [self filterStartingWith:array to:result with:searchTerm];
                }
                for (NSArray* array in data) {
                    [self filterContainsAfterFirstChar:array to:result with:searchTerm];
                }
            }
        } else {
            if (phoneShown) {
                [self filterTelephone:filteredData to:result with:searchTerm];
            } else {
                [self filterStartingWith:filteredData to:result with:searchTerm];
                [self filterContainsAfterFirstChar:filteredData to:result with:searchTerm];
            }
        }
        self.filteredData = result;
    }
    [filter release];
    filter = [searchTerm retain];
}

- (void) dealloc
{
    [filter release];
    [super dealloc];
}
@end
